#!groovy
pipeline {
  agent {
    docker {
      image 'sidovsky/android_sdk'
      args '-it --memory=4g --cpus="3"'
    }
  }

  stages {
    stage('PREPARE') {
      steps {
        sh "chmod +x gradlew"
        loadKeystores()
      }
    }
    stage ('CHECK') {
      steps {
        sh "./gradlew lint"
      }
    }
    stage('BUILD') {
      steps {
        sh "./gradlew clean assemble"
      }
    }
    stage('UNIT TEST') {
      steps {
        sh "./gradlew testDebugUnitTest -Duser.home=${env.WORKSPACE}"
      }
    }
    stage('Publish') {
      environment {
        APPCENTER_API_TOKEN = credentials('APPCENTER_API_TOKEN')
      }
      steps {
        sh "./gradlew appCenterUploadRelease"
      }
    }
  }
}

def loadKeystores() {
  def keystorePath = "./app"
  withCredentials([
    file(credentialsId: 'keystore', variable: 'keystore'),
    file(credentialsId: 'keystore_properties', variable: 'ksProperties')
  ]) {
    sh "cp -f $keystore $keystorePath/releaseKeystore.jks"
    sh "cp -f $ksProperties $keystorePath/debugKeystore.properties"
    sh "cp -f $ksProperties $keystorePath/releaseKeystore.properties"
  }
}
